### ISSUE TITLE
Not getting oputput

### ISSUE THREAD

**Issue by RenukaNale** [codebox/image_augmentor#1]
When i run python main .py C:\Users\my_pc\Desktop\ansa\model\ fliph flipv I got following op
Thread pool initialised with 3 workers
Processing C:\Users\my_pc\Desktop\ansa\model\...
Waiting for workers to complete...
{'processed': 0, 'skipped_augmented': 5, 'skipped_no_match': 1, 'error': 0}
I am expecting fliped image?

**Comment by codebox** [comment]
Have you checked for new files in the folder? The output is saying that it found 5 files that have already been augmented, so I guess you ran it more than once - the first time it created the files and on subsequent runs it skipped those files.

**Comment by RenukaNale** [comment]
Thank you for a quick reply problem solved.
