### ISSUE TITLE
Unable to obtain the augmented Images

### ISSUE THREAD

**Issue by bhavikajalli** [codebox/image_augmentor#2]
Hey, I ran the code as per the instructions and got the following output
python main.py ./test flipv
Thread pool initialised with 11 workers
Processing ./test...
Waiting for workers to complete...
{'processed': 0, 'error': 0, 'skipped_no_match': 1, 'skipped_augmented': 0}

I did check the other issue. This is the first time I ran the code with a single image in a folder called test.
I think the problem is that my image does not have a .jpg or .jpeg in its name. It just says img_0. Is there a way around this issue?

**Comment by codebox** [comment]
It looks like the image file name didn't match the format expected by the utility, take a look at the list of file extensions [here](https://github.com/codebox/image_augmentor/blob/master/main.py#L14) and update them if necessary, or just rename your file to match one of them.

**Comment by nayanmiglani** [comment]
I am getting error no module name skimage however i have installed scikit image
