### ISSUE TITLE
Error with different image resolution

### ISSUE THREAD

**Issue by steven20605** [codebox/image_augmentor#5]
I got this error for images that are 2880*1920 but works fine with 2304*1536

<img width="434" alt="00" src="https://user-images.githubusercontent.com/24932334/40931327-4d9a9f8c-685d-11e8-9426-d3749476c72e.PNG">

**Comment by codebox** [comment]
Can you upload an example image that gives this error?

**Comment by codebox** [comment]
closing - cannot reproduce, no example image provided
