### ISSUE TITLE
it doesnt work from command line

### ISSUE THREAD

**Issue by Willswag** [codebox/image_augmentor#8]
`python main.py ./positive fliph'
but its telling me in line 57 im not giving enough arguments
`ain.py ./positive fliph
  File "main.py", line 58
    print 'Usage: {} <image directory> <operation> (<operation> ...)'.format(sys.argv[0])
                                                                    ^
SyntaxError: invalid syntax
`

**Comment by codebox** [comment]
I looks like you are using python3, the utility is designed to work with python2. The code should be simple to change, either manually or using https://docs.python.org/2/library/2to3.html

**Comment by HamzahNizami** [comment]
@codebox 

I used the link you suggested and changed all the python files in the directory to python 3, but now im currently getting the following error. Any idea why?

python3 main.py ./Multi-strawbs fliph
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from multiprocessing.dummy import Pool, cpu_count
ImportError: cannot import name 'cpu_count'
