### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by dasmehdix** [codebox/image_augmentor#9]
I opened a folder named "my_images" and there are 3 images on that folder.All of them are `.jpg `format.When i use your examples,they does not work.The repo does not work.

```
C:\image_augmentor-master>python main.py ./my_images fliph flipv
  File "main.py", line 58
    print 'Usage: {} <image directory> <operation> (<operation> ...)'.format(sys.argv[0])
                                                                    ^
SyntaxError: invalid syntax

```

If the problem is cause of me please tell.
Thanks

**Comment by codebox** [comment]
It looks like you are using python3 to run the code, it is only compatible with python2

**Comment by dasmehdix** [comment]
Oh, may bad :)

Thanks for the help.
